default: &default
  adapter: your_sql
  timeout: 5000
  pool: 5
  encoding: unicode 

development:
  <<: *default
  database: your_database
  username: your_username
  password: your_password
  host: localhost

test:
  <<: *default
  database: your_database
  username: your_username
  password: your_password
  host: localhost

production:
  <<: *default
  database: your_database
  username: your_username
  password: your_password
  host: localhost