default: &default
  adapter: sqlite3
  timeout: 5000
  pool: 5
  encoding: unicode 

development:
  <<: *default
  database: db/habitatx.sqlite3

test:
  <<: *default
  database: db/habitatx.sqlite3

production:
  <<: *default
  database: db/habitatx.sqlite3
