default: &default
  adapter: sqlite3
  timeout: 5000
  pool: 5
  encoding: unicode 

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>
