default: &default
  adapter: sqlite3
  timeout: 5000
  pool: 5
  encoding: unicode 

development:
  <<: *default
  database: db/habitatx.sqlite3
  username: habitatx
  password: your_password
  host: localhost

test:
  <<: *default
  database: db/habitatx.sqlite3
  username: habitatx  
  password: your_password
  host: localhost

production:
  <<: *default
  database: db/habitatx.sqlite3
  username: habitatx
  password: your_password
  host: localhost
